import { StatusBarStyle } from "react-native";
import { normalize } from "../Utils";

// NOTE Dev: to change the primary color on Android, we gotta change the
// native style at `android/app/src/res/values/styles.xml`
export const THEME_DEFAULT_COLOR = {
    statusBarLight: "light-content" as StatusBarStyle,
    statusBarDark: "dark-content" as StatusBarStyle,
    black: "#000000",
    white: "#FFFFFF",
    danger: "red",
    success: "#0FB46F",
    warning: "yellow",
    borderColor: "#F5EFEF",
    gray: "#828282",
    info: "#3A82F7",
    oxfordBlue: "#0C2038",
    text: "#202020",
    separator: "#ccc",
    placeHolder: "#1D1D1D",
    pendingTag: "#C6C4C4",
    tabBg: "rgba(118, 118, 128, 0.24)",
    darkText: "rgba(235, 235, 245, 0.60)",
    tabButton: "#636366",
    darkGray: "#363638",
    telegarm: "#252033",
    grayLight: "#9C9CA3",
    garyLow: "#A8ADBA",
    successLight: "#69B27B",
    blackLight: "#1C1C1E",
    oxfblue: "#0C2038",
    borderBottom: "#2E2E2E",
    tabBar: "#141414",
    conisText: "#8A8080",
    addPhoto: "#7253F6",
    coinVal: "#8D8D8D",
    coinPrice: "#8D8D8D",
    sky: "#3A82F7",
    whiteLight: "#F2F4F7",
    secondary: "#EC0D12",
    overlay: "rgba(0, 0, 0, 0.80)",
    captureButton: "rgba(140, 140, 140, 0.3)",
    permissionText: "#C7C7CB",
    available: "#67CE67",
    hrline: "#2A2A2A",
    earningBorder: "#525050",
    cardBg: "#202020",
    bColor: "#333333",
    darkGray7: "#DADADA",
    lowWhite: "#E9E9EB",
    priceSection: "#4B4B4B",
    openTag: "#01C543",
    transparent: "transparent",
    username: "#828282",
    borderBottomColor: "#363636",
    textDisable: "#636363",
    earningText: "#696969",
    unSubscribeColor: "#161616",
    bordercolor: "#E7E7E7",
    backcolor: "#D3D3D3",
    linearcolor: "#D50000",
    splashlinearcolor: "#9D0000",
    unSubscribeBroderColor: "#232323",
    placeHolderColor: "#BABABA",
    samlltextColor: "#ACACAC",
    modaltext: "#7D7D7D",
    Modalborder: "#ECECEC"
};

export type ThemeColor = typeof THEME_DEFAULT_COLOR;

export const THEME_DEFAULT_FONTSIZE = {
    footprint: normalize(12),
    small: normalize(14),
    alternative: normalize(16),
    normal: normalize(18),
    regular: normalize(20),
    medium: normalize(25),
    header: normalize(42),
    inputLabel: normalize(22),
    largeSpace: normalize(54),
    large: normalize(70),
    inputText: normalize(25),
    mini: normalize(8),
    mediumEx: normalize(30),
};

export type ThemeFontSize = typeof THEME_DEFAULT_FONTSIZE;

export const THEME_DEFAULT_METRICSIZE = {
    one: normalize(1.5),
    tinyMini: normalize(2.5),
    tinySmall: normalize(4),
    tiny: normalize(5),
    tinyEx: normalize(6),
    miniXs: normalize(7),
    mini: normalize(8),
    smallXs: normalize(9),
    small: normalize(10),
    smallEx: normalize(12),
    regularXs: normalize(14),
    regular: normalize(15),
    regularEx: normalize(18),
    medium: normalize(20),
    mediumEx: normalize(22),
    sm: normalize(25),
    large: normalize(34),
    largeEx: normalize(35),
    tableRowHeight: normalize(37),
    iconSizeLargr: normalize(30),
    inputHeight: normalize(50),
    inputVerticalPadding: normalize(12),
    largeSpace: normalize(54),
    choiceHeight: normalize(70),
    longTextLineHeight: normalize(27),
    extraLarge: normalize(100),
};
export type ThemeMetricSize = typeof THEME_DEFAULT_METRICSIZE;
